name: TechTrends - Package with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Only include Python setup if you actually need it for tests
      - name: Set up Python (for testing)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Current stable LTS version

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./project
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/techtrends:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/techtrends:${{ github.sha }}