namespace: prod
replicaCount: 3 

image:
  repository: nourhans/techtrends
  tag: latest
  pullPolicy: Always 

service:
  port: 8080
  targetPort: 8080
  protocol: TCP
  type: ClusterIP

containerPort: 8080

resources:
  requests:
    memory: "512Mi"
    cpu: "400m"
  limits:
    memory: "256Mi"
    cpu: "700m"

livenessProbe:
  path: /healthz
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  enabled: false 
readinessProbe:
  path: /healthz
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  enabled: false 

metrics:
  enabled: true
  path: /metrics
  port: 8080
  enabled: false 
