namespace: prod

replicaCount: 5

image:
  repository: nourhans/techtrends
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 7111
  targetPort: 8080
  nodePort: 30008

containerPort: 7111

resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"

livenessProbe:
  enabled: false
  path: /healthz
  port: 7111
  initialDelaySeconds: 30
  periodSeconds: 10
  fail
