namespace: staging

replicaCount: 3

image:
  repository: nourhans/techtrends  
  tag: staging  
  pullPolicy: IfNotPresent

service:
  port: 8080  
  targetPort: 8080  
  protocol: TCP
  type: ClusterIP

containerPort: 8080  

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  path: /  # Or your actual health endpoint
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  path: /  # Or your actual health endpoint
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10