namespace: staging

replicaCount: 3

image:
  repository: nourhans/techtrends
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5111
  targetPort: 8080
  nodePort: 30008

containerPort: 5111

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  enabled: false
  path: /healthz
  port: 5111
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 3

readinessProbe:
  enabled: false
  path: /healthz
  port: 5111
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

metrics:
  enabled: false
  path: /metrics
  port: 5111
