namespace: staging
replicaCount: 3

image:
  repository: nourhans/techtrends  
  tag: latest  
  pullPolicy: Always 

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30008

containerPort: 3111  

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  path: /healthz  
  port: 3111
  initialDelaySeconds: 30  
  periodSeconds: 15
  failureThreshold: 3  # Allow 3 failures before restart
  enabled: false 

readinessProbe:
  path: /healthz  
  port: 3111
  initialDelaySeconds: 5  # Shorter initial delay for readiness
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  enabled: false 


metrics:
  enabled: true
  path: /metrics
  port: 3111
  enabled: false 