namespace: sandbox

replicaCount: 1

image:
  repository: nourhans/techtrends  
  tag: v1.0-sandbox  
  pullPolicy: IfNotPresent

service:
  port: 3111  
  targetPort: 3111  
  protocol: TCP
  type: ClusterIP

containerPort: 3111  

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  path: /healthz  
  port: 3111  
  initialDelaySeconds: 30  
  periodSeconds: 20  

readinessProbe:
  path: /healthz  
  port: 3111  
  initialDelaySeconds: 5  
  periodSeconds: 10  