namespace: prod

replicaCount: 3

image:
  repository: nourhans/techtrends
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30008

containerPort: 8080

resources:
  requests:
    memory: "256Mi"      # 💡 requests < limits is the best practice
    cpu: "400m"
  limits:
    memory: "512Mi"
    cpu: "700m"

livenessProbe:
  enabled: false
  path: /healthz
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  enabled: false
  path: /healthz
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

metrics:
  enabled: false
  path: /metrics
  port: 8080
