namespace: sandbox

replicaCount: 1

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

containerPort: 3111

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz
