namespace: prod  

replicaCount: 3  

image:
  repository: nourhans/techtrends
  tag: v1.0
  pullPolicy: Always

service:
  port: 8080
  targetPort: 8080
  type: ClusterIP
  protocol: TCP  

containerPort: 8080

resources:
  requests:
    memory: "256Mi"  
    cpu: "500m"
  limits:
    memory: "512Mi"  
    cpu: "1000m"

livenessProbe:
  path: /healthz  
  port: 8080
  initialDelaySeconds: 30  
  periodSeconds: 15
  failureThreshold: 3

readinessProbe:
  path: /readyz  
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80