namespace: staging
replicaCount: 3

image:
  repository: nourhans/techtrends  
  tag: latest  
  pullPolicy: IfNotPresent

service:
  port: 8080  
  targetPort: 8080  
  protocol: TCP
  type: ClusterIP

containerPort: 8080  

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  path: /healthz  
  port: 8080
  initialDelaySeconds: 30  
  periodSeconds: 15
  failureThreshold: 3  # Allow 3 failures before restart

readinessProbe:
  path: /healthz  
  port: 8080
  initialDelaySeconds: 5  # Shorter initial delay for readiness
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3


metrics:
  enabled: true
  path: /metrics
  port: 8080